services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      target: build
    command: npx nest start --watch
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
